static_resources:
  listeners:
  # Inbound network traffic listener.
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 15006
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_wss_to_wss
          upgrade_configs:
          - upgrade_type: websocket
          route_config:
            name: local_route
            virtual_hosts:
            - name: app
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: service_wss
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      transport_socket:
        name: envoy.transport_sockets.att_tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.att_tls.v3.DownstreamAttTlsContext
          attested_tls_context:
            signing_context:
              certificate:
                  filename: certs/server-cert.pem
              private_key:
                  filename: keys/server-key.pem
              attestation_token:
                  filename: attestation-token.txt
            validation_context:
              attestation_service_trusted_keys:
                  filename: attestation-service-key.pem
          downstream_tls_context:
            require_client_certificate: true
            common_tls_context:
              tls_params:
                tls_minimum_protocol_version: TLSv1_3
              tls_certificates:
              - certificate_chain:
                  filename: certs/server-cert.pem
                private_key:
                  filename: keys/server-key.pem
              validation_context:
                trust_chain_verification: ACCEPT_UNTRUSTED

  clusters:
  - name: service_wss
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_wss
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: bot
                port_value: 8501
