include:
  - ../external/genai-stack/docker-compose.yml
    
services:
  proxy-ws:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
    - "${PORT_PROXY0:-15006}:15006"
    environment:
      - MAA_ENDPOINT=sharedeus2.eus2.attest.azure.net
    command: [ "/bin/sh", "bootstrap.sh" ]
    privileged: true
    volumes:
      - /sys/kernel/security:/sys/kernel/security:rw
    networks:
      - net

  flask-bot:
    build:
      context: ./flask-bot
      dockerfile: flask-bot.Dockerfile
    volumes:
      - $PWD/embedding_model:/embedding_model
    environment:
      - NEO4J_URI=${NEO4J_URI-neo4j://database:7687}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD-password}
      - NEO4J_USERNAME=${NEO4J_USERNAME-neo4j}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL-http://host.docker.internal:11434}
      - LLM=${LLM-llama2}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL-sentence_transformer}
      - LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT-"https://api.smith.langchain.com"}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2-false}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
    networks:
      - net
    depends_on:
      database:
        condition: service_healthy
      pull-model:
        condition: service_completed_successfully
    x-develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - loader.py
            - pdf_bot.py

    ports:
      - 8504:8504    